export const GENRES = Object.values({
    vse: "Все жанры",
    boevik: "боевик",
    fentezi: "фэнтези",
    fantastika: "фантастика",
    triller: "триллер",
    voennyj: "военный",
    detektiv: "детектив",
    komediya: "комедия",
    drama: "драма",
    uzhasy: "ужасы",
    kriminal: "криминал",
    melodrama: "мелодрама",
    vestern: "вестерн",
    biografiya: "биография",
    anime: "аниме",
    detskij: "детский",
    multfilm: "мультфильм",
    "film-nuar": "фильм-нуар",
    "dlya-vzroslyh": "для взрослых",
    dokumentalnyj: "документальный",
    igra: "игра",
    istoriya: "история",
    koncert: "концерт",
    korotkometrazhka: "короткометражка",
    muzyka: "музыка",
    myuzikl: "мюзикл",
    novosti: "новости",
    priklyucheniya: "приключения",
    "realnoe-tv": "реальное ТВ",
    semejnyj: "семейный",
    sport: "спорт",
    "tok-shou": "ток-шоу",
    ceremoniya: "церемония",
});

export const COUNTRIES = Object.values({
    vse: "Все страны",
    avstraliya: "Австралия",
    avstriya: "Австрия",
    azerbajdzhan: "Азербайджан",
    albaniya: "Албания",
    alzhir: "Алжир",
    "amerikanskie-virginskie-ostrova": "Американские Виргинские острова",
    "amerikanskoe-samoa": "Американское Самоа",
    angola: "Ангола",
    andorra: "Андорра",
    antarktida: "Антарктида",
    "antigua-i-barbuda": "Антигуа и Барбуда",
    "antilskie-ostrova": "Антильские Острова",
    argentina: "Аргентина",
    armeniya: "Армения",
    aruba: "Аруба",
    afganistan: "Афганистан",
    bagamy: "Багамы",
    bangladesh: "Бангладеш",
    barbados: "Барбадос",
    bahrejn: "Бахрейн",
    belarus: "Беларусь",
    beliz: "Белиз",
    belgiya: "Бельгия",
    benin: "Бенин",
    "bereg-slonovoj-kosti": "Берег Слоновой кости",
    bermudy: "Бермуды",
    birma: "Бирма",
    bolgariya: "Болгария",
    boliviya: "Боливия",
    bosniya: "Босния",
    "bosniya-i-gercegovina": "Босния и Герцеговина",
    botsvana: "Ботсвана",
    braziliya: "Бразилия",
    "brunej-darussalam": "Бруней-Даруссалам",
    "burkina-faso": "Буркина-Фасо",
    burundi: "Бурунди",
    butan: "Бутан",
    vanuatu: "Вануату",
    vatikan: "Ватикан",
    velikobritaniya: "Великобритания",
    vengriya: "Венгрия",
    venesuela: "Венесуэла",
    "virginskie-ostrova-velikobritaniya": "Виргинские Острова (Великобритания)",
    "virginskie-ostrova-ssha": "Виргинские Острова (США)",
    "vneshnie-malye-ostrova-ssha": "Внешние малые острова США",
    vetnam: "Вьетнам",
    "vetnam-severnyj": "Вьетнам Северный",
    gabon: "Габон",
    gaiti: "Гаити",
    gajana: "Гайана",
    gambiya: "Гамбия",
    gana: "Гана",
    gvadelupa: "Гваделупа",
    gvatemala: "Гватемала",
    gvineya: "Гвинея",
    "gvineya-bisau": "Гвинея-Бисау",
    germaniya: "Германия",
    "germaniya-gdr": "Германия (ГДР)",
    "germaniya-frg": "Германия (ФРГ)",
    gibraltar: "Гибралтар",
    gonduras: "Гондурас",
    gonkong: "Гонконг",
    grenada: "Гренада",
    grenlandiya: "Гренландия",
    greciya: "Греция",
    gruziya: "Грузия",
    guam: "Гуам",
    daniya: "Дания",
    dominika: "Доминика",
    dominikana: "Доминикана",
    egipet: "Египет",
    zair: "Заир",
    zambiya: "Замбия",
    "zapadnaya-sahara": "Западная Сахара",
    zimbabve: "Зимбабве",
    izrail: "Израиль",
    indiya: "Индия",
    indoneziya: "Индонезия",
    iordaniya: "Иордания",
    irak: "Ирак",
    iran: "Иран",
    irlandiya: "Ирландия",
    islandiya: "Исландия",
    ispaniya: "Испания",
    italiya: "Италия",
    jemen: "Йемен",
    "kabo-verde": "Кабо-Верде",
    kazahstan: "Казахстан",
    "kajmanovy-ostrova": "Каймановы острова",
    kambodzha: "Камбоджа",
    kamerun: "Камерун",
    kanada: "Канада",
    katar: "Катар",
    keniya: "Кения",
    kipr: "Кипр",
    kirgiziya: "Киргизия",
    kiribati: "Кирибати",
    kitaj: "Китай",
    kolumbiya: "Колумбия",
    komory: "Коморы",
    kongo: "Конго",
    "kongo-drk": "Конго (ДРК)",
    koreya: "Корея",
    "koreya-severnaya": "Корея Северная",
    "koreya-yuzhnaya": "Корея Южная",
    kosovo: "Косово",
    "kosta-rika": "Коста-Рика",
    "kot-divuar": "Кот-д’Ивуар",
    kuba: "Куба",
    kuvejt: "Кувейт",
    laos: "Лаос",
    latviya: "Латвия",
    lesoto: "Лесото",
    liberiya: "Либерия",
    livan: "Ливан",
    liviya: "Ливия",
    litva: "Литва",
    lihtenshtejn: "Лихтенштейн",
    lyuksemburg: "Люксембург",
    mavrikij: "Маврикий",
    mavritaniya: "Мавритания",
    madagaskar: "Мадагаскар",
    makao: "Макао",
    makedoniya: "Македония",
    malavi: "Малави",
    malajziya: "Малайзия",
    mali: "Мали",
    maldivy: "Мальдивы",
    malta: "Мальта",
    marokko: "Марокко",
    martinika: "Мартиника",
    "marshallovy-ostrova": "Маршалловы острова",
    meksika: "Мексика",
    mozambik: "Мозамбик",
    moldova: "Молдова",
    monako: "Монако",
    mongoliya: "Монголия",
    montserrat: "Монтсеррат",
    myanma: "Мьянма",
    namibiya: "Намибия",
    nepal: "Непал",
    niger: "Нигер",
    nigeriya: "Нигерия",
    niderlandy: "Нидерланды",
    nikaragua: "Никарагуа",
    "novaya-zelandiya": "Новая Зеландия",
    "novaya-kaledoniya": "Новая Каледония",
    norvegiya: "Норвегия",
    oae: "ОАЭ",
    "okkupirovannaya-palestinskaya-territoriya":
        "Оккупированная Палестинская территория",
    oman: "Оман",
    "ostrov-men": "Остров Мэн",
    "ostrova-kuka": "Острова Кука",
    pakistan: "Пакистан",
    palau: "Палау",
    palestina: "Палестина",
    panama: "Панама",
    "papua-novaya-gvineya": "Папуа - Новая Гвинея",
    paragvaj: "Парагвай",
    peru: "Перу",
    polsha: "Польша",
    portugaliya: "Португалия",
    "puerto-riko": "Пуэрто Рико",
    reyunon: "Реюньон",
    "rossijskaya-imperiya": "Российская империя",
    rossiya: "Россия",
    ruanda: "Руанда",
    rumyniya: "Румыния",
    sssr: "СССР",
    ssha: "США",
    salvador: "Сальвадор",
    samoa: "Самоа",
    "san-marino": "Сан-Марино",
    "saudovskaya-araviya": "Саудовская Аравия",
    svazilend: "Свазиленд",
    "severnaya-makedoniya": "Северная Македония",
    "sejshelskie-ostrova": "Сейшельские острова",
    senegal: "Сенегал",
    "sent-vinsent-i-grenadiny": "Сент-Винсент и Гренадины",
    "sent-lyusiya": "Сент-Люсия",
    serbiya: "Сербия",
    "serbiya-i-chernogoriya": "Сербия и Черногория",
    siam: "Сиам",
    singapur: "Сингапур",
    siriya: "Сирия",
    slovakiya: "Словакия",
    sloveniya: "Словения",
    somali: "Сомали",
    sudan: "Судан",
    surinam: "Суринам",
    "serra-leone": "Сьерра-Леоне",
    tadzhikistan: "Таджикистан",
    tailand: "Таиланд",
    tajvan: "Тайвань",
    tanzaniya: "Танзания",
    "timor-leste": "Тимор-Лесте",
    togo: "Того",
    tonga: "Тонга",
    "trinidad-i-tobago": "Тринидад и Тобаго",
    tuvalu: "Тувалу",
    tunis: "Тунис",
    turkmenistan: "Туркменистан",
    turciya: "Турция",
    uganda: "Уганда",
    uzbekistan: "Узбекистан",
    ukraina: "Украина",
    urugvaj: "Уругвай",
    "farerskie-ostrova": "Фарерские острова",
    "federativnye-shtaty-mikronezii": "Федеративные Штаты Микронезии",
    fidzhi: "Фиджи",
    filippiny: "Филиппины",
    finlyandiya: "Финляндия",
    franciya: "Франция",
    "francuzskaya-gviana": "Французская Гвиана",
    "francuzskaya-polineziya": "Французская Полинезия",
    horvatiya: "Хорватия",
    car: "ЦАР",
    chad: "Чад",
    chernogoriya: "Черногория",
    chehiya: "Чехия",
    chehoslovakiya: "Чехословакия",
    chili: "Чили",
    shvejcariya: "Швейцария",
    shveciya: "Швеция",
    "shri-lanka": "Шри-Ланка",
    ekvador: "Эквадор",
    "ekvatorialnaya-gvineya": "Экваториальная Гвинея",
    eritreya: "Эритрея",
    estoniya: "Эстония",
    efiopiya: "Эфиопия",
    yuar: "ЮАР",
    yugoslaviya: "Югославия",
    "yugoslaviya-fr": "Югославия (ФР)",
    yamajka: "Ямайка",
    yaponiya: "Япония",
});

export const formatDate = (dateString: string): string => {
    const date = new Date(parseInt(dateString));
    const today = new Date();
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);
    const dayBeforeYesterday = new Date(yesterday);
    dayBeforeYesterday.setDate(dayBeforeYesterday.getDate() - 1);

    if (date.toDateString() === today.toDateString()) {
        return `Сегодня, ${date.toLocaleTimeString('ru-RU')}`;
    } else if (date.toDateString() === yesterday.toDateString()) {
        return `Вчера, ${date.toLocaleTimeString('ru-RU')}`;
    } else if (date.toDateString() === dayBeforeYesterday.toDateString()) {
        return `Позавчера, ${date.toLocaleTimeString('ru-RU')}`;
    } else {
        const options: Intl.DateTimeFormatOptions = {day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute:'2-digit'};
        return date.toLocaleDateString('ru-RU', options);
    }
}